services:

    app.menu_builder:
        class: Jaccob\AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            # We need this for the SecurityAware trait
            - [setContainer, ["@service_container"]]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createMainMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main }
