jaccob_app:
    resource: "@JaccobAppBundle/Resources/config/routing.yml"
    prefix:   /

jaccob_account:
    resource: "@JaccobAccountBundle/Resources/config/routing.yml"
    prefix:   /u

jaccob_task:
    resource: "@JaccobTaskBundle/Resources/config/routing.yml"
    prefix:   /task
