# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Jaccob\AccountBundle\Security\User\JaccobUser: bcrypt

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        jaccob:
            id: jaccob_account.account_provider

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:

        # disables authentication for assets and the profiler,
        # adapt it according to your needs
        dev:
            pattern:                  ^/(_(profiler|wdt)|css|images|js)/
            security:                 false

        # disables security on login page
        jaccob_login:
            pattern:                  ^(/u/login|/u/login/request-password)$
            security:                 false

        jaccob_home:
            pattern:                  ^/$
            security:                 false

        # enforce security on everything that needs security
        jaccob:
            pattern:                  ^/
            form_login:
                check_path:           jaccob_account.login_check
                login_path:           jaccob_account.login
                default_target_path:  jaccob_account.home
            logout:
                path:                 jaccob_account.logout
                target:               _welcome
            # allow both anonymous and authenticated users, knowing that all
            # access checks needs to be done at the controller level, harsh
            # but working... we cannot provide more than one firewall else
            # sessions will be separated
            anonymous:                ~

    access_control:
        - { path: "^/media/th/", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^(/media/view|/media/share)", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/media/album/[^/]+$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
