<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Jaccob\AccountBundle\Model\Account\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Account
 *
 * Structure class for relation public.account.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Account extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('public.account')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('mail', 'varchar')
            ->addField('user_name', 'varchar')
            ->addField('user_database', 'varchar')
            ->addField('password_hash', 'varchar')
            ->addField('salt', 'varchar')
            ->addField('key_public', 'bytea')
            ->addField('key_private', 'bytea')
            ->addField('key_type', 'varchar')
            ->addField('is_active', 'bool')
            ->addField('is_admin', 'bool')
            ->addField('validate_token', 'varchar')
            ->addField('ts_added', 'timestamp')
            ;
    }
}
