jaccob_task.add:
    path:     /add
    defaults: { _controller: "JaccobTaskBundle:Task:add" }

jaccob_task.view:
    path:     /{id}
    defaults: { _controller: "JaccobTaskBundle:Task:view" }
    requirements:
        id: \d+

jaccob_task.edit:
    path:     /{id}/edit
    defaults: { _controller: "JaccobTaskBundle:Task:edit" }
    requirements:
        id: \d+

jaccob_task.list:
    path:     /
    defaults: { _controller: "JaccobTaskBundle:Task:list" }

jaccob_task.list_starred:
    path:     /starred
    defaults: { _controller: "JaccobTaskBundle:Task:listStarred" }

jaccob_task.list_deadline:
    path:     /deadline
    defaults: { _controller: "JaccobTaskBundle:Task:listDeadline" }

jaccob_task.list_archive:
    path:     /archives
    defaults: { _controller: "JaccobTaskBundle:Task:listArchive" }
