parameters:
    jaccob_task.form.task.class: Jaccob\TaskBundle\Form\TaskType

services:

    jaccob_account.form.task:
        class: "%jaccob_task.form.task.class%"
        tags:
            - { name: form.type, alias: jaccob_taskbundle_task }
