parameters:
    jaccob.form.task.class: Jaccob\TaskBundle\Form\TaskType

services:

    jaccob_task.menu_provider:
        class: Jaccob\TaskBundle\Menu\TaskMenuProvider
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]
        tags: [{ name: knp_menu.provider }]

    jaccob.form.task:
        class: "%jaccob.form.task.class%"
        tags:
            - { name: form.type, alias: jaccob_taskbundle_task }

    jaccob_task.menu_listener:
        class: Jaccob\TaskBundle\EventListener\ConfigureMenuListener
        tags:
          - { name: kernel.event_listener, event: jaccob.menu_configure, method: onMenuConfigure }
