parameters:
    jaccob.form.task.class: Jaccob\TaskBundle\Form\TaskType

services:
#    jaccob_task.example:
#        class: Jaccob\TaskBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    jaccob.form.task:
        class: "%jaccob.form.task.class%"
        tags:
            - { name: form.type, alias: jaccob_taskbundle_task }
