jaccob_media.home:
    path:     /
    defaults: { _controller: "JaccobMediaBundle:Home:home" }

jaccob_media.album.list:
    path:     /album/{albumId}
    defaults: { _controller: "JaccobMediaBundle:Album:list" }
    requirements:
        albumId: \d+

jaccob_media.album.add:
    path:     /new-album
    defaults: { _controller: "JaccobMediaBundle:Album:create" }

jaccob_media.album.create_from:
    path:     /import
    defaults: { _controller: "JaccobMediaBundle:Album:createFrom" }

jaccob_media.media.view:
    path:     /view/{mediaId}
    defaults: { _controller: "JaccobMediaBundle:Media:view" }
    requirements:
        mediaId: \d+

jaccob_media.media.view:
    path:     /view/{mediaId}/{size}
    defaults: { _controller: "JaccobMediaBundle:Media:view" }
    requirements:
        mediaId: \d+

jaccob_media.album.import:
    path:     /{albumId}/import
    defaults: { _controller: "JaccobMediaBundle:Album:import" }
    requirements:
        albumId: \d+

jaccob_media.media.thumbnail:
    path:     /{path}
    defaults: { _controller: "JaccobMediaBundle:Thumbnail:create" }
    requirements:
        path: "^.+"
