jaccob_media.home:
    path:     /
    defaults: { _controller: "JaccobMediaBundle:Home:home" }

jaccob_media.share.token:
    path:     /share/{albumId}/{token}
    defaults: { _controller: "JaccobMediaBundle:Share:token" }
    requirements:
        albumId: \d+

jaccob_media.share.token_password:
    path:     /share/{albumId}/{token}/password
    defaults: { _controller: "JaccobMediaBundle:Share:tokenPassword" }
    requirements:
        albumId: \d+

jaccob_media.album.view:
    path:     /album/{albumId}
    defaults: { _controller: "JaccobMediaBundle:Album:list" }
    requirements:
        albumId: \d+

jaccob_media.album.share:
    path:     /album/{albumId}/share
    defaults: { _controller: "JaccobMediaBundle:Album:shareForm" }
    requirements:
        albumId: \d+

jaccob_media.album.edit:
    path:     /album/{albumId}/edit
    defaults: { _controller: "JaccobMediaBundle:Album:editForm" }
    requirements:
        albumId: \d+

jaccob_media.album.delete:
    path:     /album/{albumId}/delete
    defaults: { _controller: "JaccobMediaBundle:Album:delete" }
    requirements:
        albumId: \d+

jaccob_media.album.add:
    path:     /new-album
    defaults: { _controller: "JaccobMediaBundle:Album:create" }

jaccob_media.album.external_import:
    path:     /import
    defaults: { _controller: "JaccobMediaBundle:Album:import" }

jaccob_media.album.create_from:
    path:     /import/local
    defaults: { _controller: "JaccobMediaBundle:Album:createFrom" }

jaccob_media.media.view:
    path:     /view/{mediaId}
    defaults: { _controller: "JaccobMediaBundle:Media:view" }
    requirements:
        mediaId: \d+

jaccob_media.media.edit:
    path:     /view/{mediaId}/edit
    defaults: { _controller: "JaccobMediaBundle:Media:editForm" }
    requirements:
        mediaId: \d+

jaccob_media.media.delete:
    path:     /view/{mediaId}/delete
    defaults: { _controller: "JaccobMediaBundle:Media:delete" }
    requirements:
        mediaId: \d+

jaccob_media.media.view.full:
    path:     /view/{mediaId}/fullscreen
    defaults: { _controller: "JaccobMediaBundle:Media:viewFullscreen" }
    requirements:
        mediaId: \d+

jaccob_media.album.import:
    path:     /{albumId}/import
    defaults: { _controller: "JaccobMediaBundle:Album:import" }
    requirements:
        albumId: \d+

jaccob_media.media.thumbnail:
    path:     /th/{path}
    defaults: { _controller: "JaccobMediaBundle:Thumbnail:create" }
    requirements:
        path: "^.+"
