parameters:

    # @todo Those next two could be remove or determined
    # dynamically using the bundle routing prefix to avoid
    # problems
    jaccob_media.directory.public: /var/www/jaccob/web/media
    jaccob_media.directory.relative: media
    jaccob_media.directory.upload: /data/private/photos

    # Allowed media sizes
    jaccob_media.size.list: [240, 480,  720, 960, 1200, 1440, full]
    jaccob_media.size.fullscreen: 1440
    jaccob_media.size.default: 720

services:

    jaccob_media.twig.thumbnail:
        class: Jaccob\MediaBundle\Twig\ThumbnailExtension
        tags: [{ name: twig.extension }]
        calls:
            - [setContainer, ["@service_container"]]

    jaccob_media.menu_provider:
        class: Jaccob\MediaBundle\Menu\MediaMenuProvider
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]
        tags: [{ name: knp_menu.provider }]

    jaccob_media.menu_listener:
        class: Jaccob\MediaBundle\EventListener\ConfigureMenuListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
          - { name: kernel.event_listener, event: jaccob.menu_configure, method: onMenuConfigure }

    jaccob_media.importer:
        class: Jaccob\MediaBundle\Import\FilesystemImporter
        calls:
            - [setContainer, ["@service_container"]]

    jaccob_media.type_finder:
        class: Jaccob\MediaBundle\Type\TypeFinderService

    jaccob_media.type.image:
        class: Jaccob\MediaBundle\Type\ImageType
        arguments:
            - image/gif
            - image/jpeg
            - image/png
            - image/svg+xml
            - image/vnd.microsoft.icon
        tags: [{ name: jaccob_media.type }]
        calls:
            - [setContainer, ["@service_container"]]
