parameters:

    jaccob_media.directory.public: /var/www/jaccob/web/media
    jaccob_media.directory.upload: /data/private/photos

services:

    jaccob_media.menu_provider:
        class: Jaccob\MediaBundle\Menu\MediaMenuProvider
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]
        tags: [{ name: knp_menu.provider }]

    jaccob_media.menu_listener:
        class: Jaccob\MediaBundle\EventListener\ConfigureMenuListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
          - { name: kernel.event_listener, event: jaccob.menu_configure, method: onMenuConfigure }

    jaccob_media.importer:
        class: Jaccob\MediaBundle\Import\FilesystemImporter
        calls:
            - [setContainer, ["@service_container"]]
