<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Jaccob\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Session
 *
 * Structure class for relation public.session.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Session extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('public.session')
            ->setPrimaryKey(['id'])
            ->addField('id', 'varchar')
            ->addField('created', 'timestamp')
            ->addField('touched', 'timestamp')
            ->addField('data', 'bytea')
            ;
    }
}
