jaccob_account.home:
    path:     /
    defaults: {_controller: 'JaccobAccountBundle:Default:index'}

jaccob_account.login:
    path:     /login
    defaults: { _controller: 'JaccobAccountBundle:Security:login' }

jaccob_account.request_password:
    path:     /login/request-password
    defaults: { _controller: 'JaccobAccountBundle:Security:requestPassword' }

jaccob_account.change_password:
    path:     /change-password
    defaults: { _controller: 'JaccobAccountBundle:Security:changePassword' }

jaccob_account.one_time_login:
    path:     /login/one/{accountId}/{token}
    defaults: { _controller: 'JaccobAccountBundle:Security:oneTimeLogin' }

jaccob_account.login_check:
    path:     /login/go

jaccob_account.logout:
    path:     /logout

jaccob_account.profile_view:
    path:     /{id}
    defaults: { _controller: 'JaccobAccountBundle:Account:view' }
    requirements:
        id: \d+
