services:
    jaccob_account_provider:
        class: 'Jaccob\AccountBundle\Security\User\JaccobAccountProvider'
        calls:
          - [setAccountSession, ["@=service('pomm').getSession('account')"]]
